### ISSUE TITLE
Linked images are not always loading

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#11]
Fix was contained in https://github.com/johannesnoordanus/svg2gcode/pull/9

Without it this scenario can happen (png is in the same folder as the svg):
```
❯ svg2gcode --constantburn --pixelsize 0.06 --imagespeed 6000 --cuttingspeed 400 --splitfile --cuttingpower 1000 /tmp/dessin.svg /tmp/test.nc
xlink:href="dessin.png"
Image data error: neither file nor data!
```

**Comment by johannesnoordanus** [comment]
I included your fix. It is a bit tedious to solve merge conflicts, but I hope I didn't make typos.
Nice updates by the way!
