### ISSUE TITLE
Svg2gcode & image2gcode are broken since 2.6.0

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#12]
With recent versions, those tools don't do anything on my engraver (both using serial and SDCard, so it's really the gcode).

After a while, I figured svg2gcode#f018ca4e07b1c7c39f742610df4acd509da5f5f3 was guilty.
A little while after I figured it's because of the new comments using extra long lines, while gcode recommends short lines (I couldn't find a rock solid reference but 50 characters seems safe) to work on every hardware.

**Comment by johannesnoordanus** [comment]
> With recent versions, those tools don't do anything on my engraver (both using serial and SDCard, so it's really the gcode).
> 
> After a while, I figured svg2gcode#f018ca4e07b1c7c39f742610df4acd509da5f5f3 was guilty. A little while after I figured it's because of the new comments using extra long lines, while gcode recommends short lines (I couldn't find a rock solid reference but 50 characters seems safe) to work on every hardware.

Ok, thanks, I should have been more careful about that.
I'll fix that soon!

**Comment by johannesnoordanus** [comment]
Pretty-print version 2.6.3 of svg2gcode, that should fix the comment line size issue. 
This runs on my machines without problem.

**Comment by johannesnoordanus** [comment]
Pretty-print version 2.6.2 of image2gcode, that should fix the comment line size issue.
This runs on my machines without problem.

**Comment by johannesnoordanus** [comment]
I would like to close this

**Comment by fdev31** [comment]
Will probably give it a chance a bit later today. I'll probably release my halftone converter as a standalone script, it plays very well with image2gcode... but I want to do more tests.

**Comment by fdev31** [comment]
Works great!
