### ISSUE TITLE
Incorrect power for image's left & right borders

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#6]
When burning an image, the "black" pixels which are on the extreme left or right of an image get a lower power/shorter duration (get less burned) than pixels which are in the middle of a line - this can be very significant in some materials.

**Comment by johannesnoordanus** [comment]
I did not notice this issue and tested several engravings having a border.
Maybe this has to do with the type of machine you are using, and/or the drawing speed.
I use laser burning 'M4' mode which autocorrects power for speed changes (which occur at the reft and right edges).
One way to test this is to replace 'M4' within the gcode files (produced by svg2gcode) with 'M3' (constant power independent of head speed). This (should) result in a little 'overburn' at the left and right edges of the image. 
Reducing the head speed might also give a different result.

**Comment by fdev31** [comment]
Thanks for the hints!
I'm using max speed as much as possible (6000 mm/min in my case).
I'll keep you informed when I have a chance to make some proper testing of M3 vs M4.

**Comment by fdev31** [comment]
I finally had time to do some tests `M4` vs `M3`, the results were a bit surprising to me...
![1691605202147](https://github.com/johannesnoordanus/svg2gcode/assets/238622/25c0056c-8104-49cc-b6f2-fb3e2e16b0ff)
from bottom to top in this picture:

- ref settings (power: 400)
- change to M3 (power: 400)
- change to M3 (power: 200)

All tests are done at max speed with same pixel size (0.06).
Note that the ref setting isn't very powerful to make the problem more visible.

So besides the "burned" vs "dimmed" border choice which is the topic of this bug, it also looks like there is a HUGE power penalty using M4.

Is it specific to my laser or do you experience the same behavior?

About our initial topic, I don't get how middle "thin lines" don't suffer from those issues (burned or dimmed) while the extreme ones have it... it sounds like having some kind of "padding" on extremes, like traveling a little with the laser off as if we were going to burn something else before changing direction would fix the issue...

**Comment by fdev31** [comment]
Wouldn't adding a "fake" pixel using a minimal power (1% ?) 1mm far from each border would solve the problems ? (both `M4` & `M3`, solving the power loss issue at the same time since your code leads to relatively constant speeds it looks quite good to me if you ignore the over burn...)

**Comment by fdev31** [comment]
I just tested it by editing the image to add left & right pixels in the brightest grey shade and got wonderful results even with `M3`. I can use less than half the power setting by using `M3` and it looks like the same applies for cut (not suffixed) gcode - meaning I can cut way more than I tested :dancers:

**Comment by johannesnoordanus** [comment]
Very interesting. Especially you using .06mm^2 pixels. I test using .1 mm^2.
Very clever to update the picture to get a good result.
I am not sure what is happening with the end pixels. I will have to do some tests myself.
But it does look like an issue separate from M3 vs M4 (your conclusion also I believe).
Very interesting what you mention about power loss using M4 mode. I was a bit worried about that, but I did not test it separately.
It would be a huge win/gain it this is true (I will come back on that).

**Comment by fdev31** [comment]
I added the `--mode` option in my PR (which is very messy, should be split) which makes it convenient to test M4 vs M3 ;) (ok, actually in this specific case, editing the file can be faster :D)

**Comment by johannesnoordanus** [comment]
Option --constantburn is added for this purpose!
(But thanks!)

**Comment by johannesnoordanus** [comment]
I am implementing --overscan <#br of pixels> right now.

**Comment by johannesnoordanus** [comment]
Ok, version 2.6.0 of image2gcode has option --overscan (later on I will add this to svg2gcode).
Note that '--overscan 0', which is the default, doesn't alter the code path of render code, so this should give the exact results as before. I did some test (by coloring the overscan pixels) and this looks ok to me.
I did not (yet) run this on the laser machine.

**Comment by fdev31** [comment]
Great! :)
By the way, why not sharing the code / having libraries so both would always be in sync ?

Ad-hoc note, I'm back home and can use my stuff...
I see grblhud requires scikit-images because of the gcode2image dependency... I think it would be great to have it optional for people using it in command line only (typical use case is like mine: a raspberry pi is plugged to the machine and is used as a server).
At the moment it makes the installation fail on a raspberry because of the required scikit-image version (not even talking about the crazy amount of time to install this + numpy from pypi).

**Comment by johannesnoordanus** [comment]
> Great! :) By the way, why not sharing the code / having libraries so both would always be in sync ?
> 
> Ad-hoc note, I'm back home and can use my stuff... I see grblhud requires scikit-images because of the gcode2image dependency... I think it would be great to have it optional for people using it in command line only (typical use case is like mine: a raspberry pi is plugged to the machine and is used as a server). At the moment it makes the installation fail on a raspberry because of the required scikit-image version (not even talking about the crazy amount of time to install this + numpy from pypi).

Ok, I was thinking about that, I will update it accordingly.
As a side note: I found this info about flit https://betterprogramming.pub/a-pyproject-toml-developers-cheat-sheet-5782801fb3ed
You mentioned editable installs: 'pip install -e' and according to the document above, this should just work!

**Comment by johannesnoordanus** [comment]
Updated grblhud to version 1.6.1

**Comment by fdev31** [comment]
I didn't test it yet but I'm pretty sure this is doing the job. Thanks!

About the link you mention, It looks like he just adds the `pyproject.toml` file to the project, so that's expected (this file is standard). Check "A Clean Package Structure" in this page.

**Comment by johannesnoordanus** [comment]
> By the way, why not sharing the code / having libraries so both would always be in sync ?

The reason not to do this, until now, was that image2gcode and svg2gcode have different requirements. Svg2gcode needs transformations for example and depends on other types (like Vector).
So it took quite a bit of work to generalise this code and make it 'type independent'.

But now we have image2gcode version 2.8.2 that doubles as a library, and svg2gcode 2.8.1 that uses this library.
As consequence svg2gcode now has options --overscan and --showoverscan (to check).

**Comment by johannesnoordanus** [comment]
> About the link you mention, It looks like he just adds the `pyproject.toml` file to the project, so that's expected (this file is standard). Check "A Clean Package Structure" in this page.

I have seen that. But the point is that that editable installs depend on the version of pip (and flit) so it supports [PEP] 660 (https://peps.python.org/pep-0660/ etc.). It is independent of the package structure, as far as I can see.
I use a minimal package structure, which makes things clear and easy to oversee (and is a direct reflection of the python package ordering).

**Comment by fdev31** [comment]
Yes, the only relevant file is the `pyproject.toml` (as in the PEP title) - before that it was `setup.py` (still supported) - flit, pip, poetry, python-build, etc... are just tools using the standard interface(s). Nobody wants to learn the specific choice of tool of another dev - we each have different tastes. The package structure is flexible as long as it's properly declared in the pyproject file.

About overscan it's great, I'll try to test it soon :)

**Comment by johannesnoordanus** [comment]
> When burning an image, the "black" pixels which are on the extreme left or right of an image get a lower power/shorter duration (get less burned) than pixels which are in the middle of a line - this can be very significant in some materials.

I did some tests today, but I cannot reproduce this on my laser machine (using a 5W and a 10W head). M3 or M4 does not make a difference. All lines are perfectly drawn at the edges.
I added a calibration option to image2gcode, this creates several files to be able to do that. On the image here you can see two 2cmx2cm squares that contain a gradient, one horizontal (banding) and one diagonal. I calibrated the 5W head so it has black just a bit too much (off centre) which gave the image focused on:

![laser_image](https://github.com/johannesnoordanus/svg2gcode/assets/52376919/e551ec95-b0a6-4a39-99bc-efa5069666aa)
(note that I took the picture at an angle to get rid of all kinds of pattern interference, also, the image is way too yellow because of the lamp above it; it is just to give an impression of the result.)

I ended up with a speed of 1200 (mm/min) instead of 800 I thought before was the best setting. A speed of 1400 (mm/min) gave the perfect black and white balance, but images produced with that setting where a bit washed out.
Note that the image above does not do right to the print itself (on oak) because this looks smooth and absolute perfect at a small distance. Because of relief it is viewable at 160° which is very nice.

**Comment by fdev31** [comment]
Your results look gorgeous.
I'm experimenting now, I think it looks fine :)
I am wondering how it works exactly because I had my engraver homed, the image contains a some margin + I added 5 pixels overscan and still the results looks more "trimmed" on the left (instead of adding a 5px margin ?) - it's closer to the border than I expected.

**Comment by johannesnoordanus** [comment]
> Your results look gorgeous.

Thanks!
> I'm experimenting now, I think it looks fine :)
> I am wondering how it works exactly because I had my engraver homed, the image contains a some margin + I added 5 pixels overscan and still the results looks more "trimmed" on the left (instead of adding a 5px margin ?) - it's closer to the border than I expected.

Ok, you can add option 'showoverscan' to see the outline created. If overscan 'hits the borders' it takes the border as the last overscan pixel. So it might be that overscan is less than 5 pixels. The overscan 'stays within the image size' it does not add pixels left or right.
